jobs:
  - name: selenium-manifest
    type: manifest
    steps:
     - IN: selenium-python
     - IN: selenium-test
     - TASK: managed

  - name: selenium-deploy-1
    type: deploy
    steps:
      - IN: selenium-manifest
      - IN: docker-opts
      - IN: selenium
      - TASK: managed
        deployMethod: replace
